vich_uploader:
    db_driver: orm

    mappings:
        imagenes_obra:
            delete_on_update: true
            delete_on_remove: true
            uri_prefix: '%ruta_imagenes_admin%'
            upload_destination: '%kernel.project_dir%%public%%ruta_imagenes%'
        archivo_documento:
            uri_prefix: '%ruta_documentos_admin%'
            upload_destination: '%kernel.project_dir%%public%%ruta_documentos%'
