vich_uploader:
    db_driver: orm

    mappings:
        imagenes_obra:
            uri_prefix: /obras/imagenes
            upload_destination: '%kernel.project_dir%/public/obras/imagenes'
        archivo_documento:
            uri_prefix: /documentos
            upload_destination: '%kernel.project_dir%/public/documentos'
