vich_uploader:
    db_driver: orm

    mappings:
        imagenes_obra:
            uri_prefix: '%ruta_imagenes_admin%'
            upload_destination: '%kernel.project_dir%/public/obras/imagenes'
        archivo_documento:
            uri_prefix: '%ruta_documentos%'
            upload_destination: '%kernel.project_dir%/public/documentos'
